#include "OutputSink.hpp"
#include <cctype>
#include <format>
#include <fstream>

namespace velox::cooker
{

namespace
{

    constexpr std::string_view k_HeaderPreamble =
        "#pragma once\n"
        "// Auto-generated by tools/shader_cooker -- do not edit manually.\n"
        "#include <string_view>\n"
        "\n"
        "namespace OceanFFT::Shaders\n"
        "{\n"
        "\n";

    constexpr std::string_view k_HeaderEpilogue = "} // namespace OceanFFT::Shaders\n";

    std::string MakeIdentifier(std::string_view name, std::string_view suffix)
    {
        std::string identifier{ "k_" };
        identifier.reserve(name.size() + suffix.size() + 2u);

        for (char character : name)
        {
            identifier += std::isalnum(static_cast<unsigned char>(character)) != 0 ? character : '_';
        }

        for (char character : suffix)
        {
            identifier += std::isalnum(static_cast<unsigned char>(character)) != 0 ? character : '_';
        }

        return identifier;
    }

    std::string EmitSourceLiteral(std::string_view identifier, std::string_view wgsl)
    {
        return std::format("inline constexpr std::string_view {} = R\"WGSL_END(\n{})WGSL_END\";\n",
                           identifier,
                           wgsl);
    }

} // namespace

OutputSink::OutputSink() noexcept = default;
OutputSink::~OutputSink() = default;

FileOutputSink::FileOutputSink(std::filesystem::path path) :
    path{ std::move(path) },
    description{}
{
    description = this->path.string();
}

FileOutputSink::~FileOutputSink() = default;

CookResult<void> FileOutputSink::Write(std::string_view content)
{
    const std::filesystem::path parentDirectory = path.parent_path();
    if (!parentDirectory.empty() && !std::filesystem::exists(parentDirectory))
    {
        std::filesystem::create_directories(parentDirectory);
    }

    if (!parentDirectory.empty() && !std::filesystem::is_directory(parentDirectory))
    {
        return std::unexpected(CookError::OutputPathInvalid);
    }

    std::ofstream stream{ path, std::ios::binary | std::ios::trunc };
    if (!stream.is_open())
    {
        return std::unexpected(CookError::OutputWriteFailed);
    }

    stream.write(content.data(), static_cast<std::streamsize>(content.size()));
    if (!stream.good())
    {
        return std::unexpected(CookError::OutputWriteFailed);
    }

    return {};
}

std::string_view FileOutputSink::Describe() const noexcept
{
    return description;
}

MemoryOutputSink::MemoryOutputSink() noexcept = default;
MemoryOutputSink::~MemoryOutputSink() = default;

CookResult<void> MemoryOutputSink::Write(std::string_view new_content)
{
    content.assign(new_content);
    return {};
}

std::string_view MemoryOutputSink::Describe() const noexcept
{
    return "<memory>";
}

std::string_view MemoryOutputSink::GetContent() const noexcept
{
    return content;
}

std::string GenerateShaderHeader(std::span<const CompiledVariant> variants)
{
    std::string header;
    header.reserve(1u << 20);
    header += k_HeaderPreamble;

    for (const CompiledVariant& variant : variants)
    {
        for (const CompiledEntryPoint& entryPoint : variant.EntryPoints)
        {
            const std::string identifier = MakeIdentifier(entryPoint.Name, entryPoint.VariantSuffix);
            header += EmitSourceLiteral(identifier, entryPoint.Code);
        }
    }

    header += k_HeaderEpilogue;
    return header;
}

} // namespace velox::cooker
