#include "ShaderLibraryEmitter.hpp"
#include <cctype>
#include <format>

namespace velox::cooker
{

namespace
{

    constexpr std::string_view k_GeneratedBanner =
        "// Auto-generated by tools/shader_cooker. Do not edit by hand.\n";

    std::string MakeTypeIdentifier(std::string_view name)
    {
        std::string identifier;
        identifier.reserve(name.size());

        for (char character : name)
        {
            identifier += std::isalnum(static_cast<unsigned char>(character)) != 0 ? character : '_';
        }

        return identifier;
    }

    std::string_view ToLiteral(bool value) noexcept
    {
        return value ? "true" : "false";
    }

    std::string EnumeratorFor(std::string_view enum_name, std::string_view value_name)
    {
        return std::format("velox::{}::{}", enum_name, value_name);
    }

    std::string BindingKindEnumerator(BindingKind kind)
    {
        return EnumeratorFor("BindingKind", ToString(kind));
    }

    std::string_view VertexScalarTypeEnumeratorName(VertexScalarType scalar_type) noexcept
    {
        switch (scalar_type)
        {
        case VertexScalarType::Float16:
            return "Float16";
        case VertexScalarType::Float32:
            return "Float32";
        case VertexScalarType::SignedInteger32:
            return "SignedInteger32";
        case VertexScalarType::UnsignedInteger32:
            return "UnsignedInteger32";
        case VertexScalarType::Invalid:
            return "Invalid";
        }

        return "Invalid";
    }

    /** The whole raster payload passes through this one function.
     *
     * The engine's RenderTarget type lands in parallel with this work. Keeping the emission in one
     * place makes the remap one function body instead of a search through the emitter. */
    std::string EmitRasterState(const ReflectedRasterState& raster, size_t index)
    {
        std::string emitted;

        if (raster.VertexInputs.empty())
        {
            emitted += std::format("constexpr velox::VertexAttributeInfo k_VertexInputs{}[1]{{}};\n", index);
            emitted += std::format("constexpr uint32_t k_VertexInputCount{} = 0u;\n", index);
        }
        else
        {
            emitted += std::format("constexpr velox::VertexAttributeInfo k_VertexInputs{}[]{{\n", index);
            for (const ReflectedVertexInput& input : raster.VertexInputs)
            {
                emitted += std::format("    velox::VertexAttributeInfo{{ \"{}\", {}u, {}u, {}, {}u }},\n",
                                       input.SemanticName,
                                       input.SemanticIndex,
                                       input.Location,
                                       EnumeratorFor("VertexScalarType",
                                                     VertexScalarTypeEnumeratorName(input.ScalarType)),
                                       input.ComponentCount);
            }
            emitted += "};\n";
            emitted += std::format("constexpr uint32_t k_VertexInputCount{} = {}u;\n",
                                   index,
                                   raster.VertexInputs.size());
        }

        if (raster.ColorTargets.empty())
        {
            emitted += std::format("constexpr velox::ColorTargetInfo k_ColorTargets{}[1]{{}};\n", index);
            emitted += std::format("constexpr uint32_t k_ColorTargetCount{} = 0u;\n", index);
        }
        else
        {
            emitted += std::format("constexpr velox::ColorTargetInfo k_ColorTargets{}[]{{\n", index);
            for (const ReflectedColorTarget& target : raster.ColorTargets)
            {
                emitted += std::format("    velox::ColorTargetInfo{{ {}u, {}, {}u }},\n",
                                       target.Location,
                                       EnumeratorFor("VertexScalarType",
                                                     VertexScalarTypeEnumeratorName(target.ScalarType)),
                                       target.ComponentCount);
            }
            emitted += "};\n";
            emitted += std::format("constexpr uint32_t k_ColorTargetCount{} = {}u;\n",
                                   index,
                                   raster.ColorTargets.size());
        }

        emitted += std::format("constexpr bool k_WritesFragDepth{} = {};\n\n",
                               index,
                               raster.WritesFragDepth ? "true" : "false");
        return emitted;
    }

    std::string EmitRasterRecordFields(size_t index)
    {
        return std::format("k_VertexInputs{}, k_VertexInputCount{}, k_ColorTargets{}, "
                           "k_ColorTargetCount{}, k_WritesFragDepth{}",
                           index,
                           index,
                           index,
                           index,
                           index);
    }

    /** Splits a long source at a line end and emits the pieces as adjacent literals. The compiler
     * joins them, so the value is unchanged. */
    std::string EmitChunkedLiteral(std::string_view text)
    {
        std::string emitted;
        emitted.reserve(text.size() + (text.size() / k_MaxStringLiteralBytes + 1u) * 24u);

        size_t offset = 0u;
        while (offset < text.size())
        {
            size_t chunkEnd = offset + k_MaxStringLiteralBytes;
            if (chunkEnd >= text.size())
            {
                chunkEnd = text.size();
            }
            else
            {
                const size_t lineEnd = text.rfind('\n', chunkEnd);
                if (lineEnd != std::string_view::npos && lineEnd > offset)
                {
                    chunkEnd = lineEnd + 1u;
                }
            }

            emitted += "\nR\"WGSL(";
            emitted += text.substr(offset, chunkEnd - offset);
            emitted += ")WGSL\"";
            offset = chunkEnd;
        }

        if (emitted.empty())
        {
            emitted = "\nR\"WGSL()WGSL\"";
        }

        return emitted;
    }

    std::string MakeUniformMemberTableName(size_t layout_index, size_t binding_index)
    {
        return std::format("k_Members_L{}_B{}", layout_index, binding_index);
    }

    /** One table for each uniform block of each layout. A block with no members emits nothing, and
     * its BindingInfo takes an empty span. */
    std::string EmitUniformMemberTable(const ReflectedBinding& binding,
                                       size_t layout_index,
                                       size_t binding_index)
    {
        if (binding.UniformMembers.empty())
        {
            return {};
        }

        std::string emitted = std::format("constexpr velox::UniformMemberInfo {}[]{{\n",
                                          MakeUniformMemberTableName(layout_index, binding_index));
        for (const ReflectedUniformMember& member : binding.UniformMembers)
        {
            emitted += std::format("    velox::UniformMemberInfo{{ \"{}\", {}u, {}u, {}u }},\n",
                                   member.Name,
                                   member.Offset,
                                   member.Size,
                                   member.ArrayCount);
        }
        emitted += "};\n";
        return emitted;
    }

    std::string EmitBindingRow(const ReflectedBinding& binding, std::string_view member_table_name)
    {
        std::string row = std::format("    velox::BindingInfo{{ \"{}\", {}u, {}u, {}",
                                      binding.Name,
                                      binding.Group,
                                      binding.Binding,
                                      BindingKindEnumerator(binding.Kind));

        row += std::format(", {}u, {}ull, {}u", binding.ElementStride, binding.ByteSize, binding.ArrayCount);
        row += std::format(", {}", EnumeratorFor("ResourceShape", ToString(binding.Shape)));
        row += std::format(", {}", EnumeratorFor("TextureSampleType", ToString(binding.SampleType)));
        row += std::format(", velox::TextureFormat{{ {} }}", static_cast<uint32_t>(binding.StorageFormat));
        row += std::format(", velox::StorageTextureAccess{{ {} }}",
                           static_cast<uint32_t>(binding.StorageAccess));
        row += std::format(", velox::SamplerBindingType{{ {} }}",
                           static_cast<uint32_t>(binding.SamplerType));
        row += std::format(", {}ull", binding.Derived.ElementCount);
        row += std::format(", {}u, {}u, {}u",
                           binding.Derived.ExtentX,
                           binding.Derived.ExtentY,
                           binding.Derived.ExtentZ);

        if (member_table_name.empty())
        {
            row += ", {}";
        }
        else
        {
            row += std::format(", {}", member_table_name);
        }

        row += " },\n";
        return row;
    }

    std::string EmitPermutationStruct(const CookedModule& module)
    {
        const std::string typeName = std::format("{}Permutation", MakeTypeIdentifier(module.Name));
        std::string emitted = std::format(
            "/** The permutation axes of module {}. Defaults are the first value of each axis. */\n"
            "struct {}\n{{\n",
            module.Name,
            typeName);

        for (const PermutationAxis* axis : *module.Space)
        {
            const std::string field = MakeFieldIdentifier(axis->Name);
            const PermutationValue& first = axis->Values.front();

            if (std::holds_alternative<bool>(first))
            {
                emitted += std::format("    bool {}{{ {} }};\n", field, ToLiteral(std::get<bool>(first)));
            }
            else if (std::holds_alternative<uint32_t>(first))
            {
                emitted +=
                    std::format("    uint32_t {}{{ {}u }};\n", field, std::get<uint32_t>(first));
            }
            else
            {
                emitted += std::format("    int32_t {}{{ {} }};\n", field, std::get<int32_t>(first));
            }
        }

        emitted += "};\n\n";
        return emitted;
    }

    /** One switch for each axis, mapping a value to its slot. A call site usually passes a constant,
     * so the compiler folds the whole lookup away. */
    std::string EmitAxisIndexHelper(const CookedModule& module, const PermutationAxis& axis)
    {
        const std::string typeName = std::format("{}Permutation", MakeTypeIdentifier(module.Name));
        const std::string field = MakeFieldIdentifier(axis.Name);

        // A two-value bool axis covers every case, so a switch with a default draws C4809. A ternary
        // says the same thing and keeps the generated code clean at /W4.
        if (axis.Values.size() == 2u && std::holds_alternative<bool>(axis.Values.front()))
        {
            return std::format("constexpr uint32_t IndexOf{}{}(const {}& permutation) noexcept\n{{\n"
                               "    return permutation.{} ? {}u : {}u;\n}}\n\n",
                               MakeTypeIdentifier(module.Name),
                               field,
                               typeName,
                               field,
                               std::get<bool>(axis.Values.front()) ? 0u : 1u,
                               std::get<bool>(axis.Values.front()) ? 1u : 0u);
        }

        std::string emitted = std::format(
            "constexpr uint32_t IndexOf{}{}(const {}& permutation) noexcept\n{{\n    switch "
            "(permutation.{})\n    {{\n",
            MakeTypeIdentifier(module.Name),
            field,
            typeName,
            field);

        for (size_t i = 0u; i < axis.Values.size(); ++i)
        {
            const PermutationValue& value = axis.Values[i];
            if (std::holds_alternative<bool>(value))
            {
                emitted += std::format("    case {}:\n        return {}u;\n",
                                       ToLiteral(std::get<bool>(value)),
                                       i);
            }
            else if (std::holds_alternative<uint32_t>(value))
            {
                emitted +=
                    std::format("    case {}u:\n        return {}u;\n", std::get<uint32_t>(value), i);
            }
            else
            {
                emitted += std::format("    case {}:\n        return {}u;\n", std::get<int32_t>(value), i);
            }
        }

        emitted += "    default:\n        return 0u;\n    }\n}\n\n";
        return emitted;
    }

    std::string ValueToCppLiteral(const PermutationValue& value)
    {
        if (std::holds_alternative<bool>(value))
        {
            return std::string{ ToLiteral(std::get<bool>(value)) };
        }

        if (std::holds_alternative<uint32_t>(value))
        {
            return std::format("{}u", std::get<uint32_t>(value));
        }

        return std::to_string(std::get<int32_t>(value));
    }

    /** Fills every disabled axis with its first value, so all values a caller could pass for a dead
     * axis resolve to one variant. That is true, and it means a caller never has to know which axes
     * depend on which. */
    std::string EmitCanonicalize(const CookedModule& module)
    {
        const std::string typeName = std::format("{}Permutation", MakeTypeIdentifier(module.Name));
        std::string emitted =
            std::format("constexpr {} Canonicalize({} permutation) noexcept\n{{\n", typeName, typeName);

        for (const PermutationAxis* axis : *module.Space)
        {
            if (axis->Parent == nullptr)
            {
                continue;
            }

            emitted += std::format("    if (permutation.{} != {})\n    {{\n        permutation.{} = {};\n"
                                   "    }}\n",
                                   MakeFieldIdentifier(axis->Parent->Name),
                                   ValueToCppLiteral(axis->RequiredParentValue),
                                   MakeFieldIdentifier(axis->Name),
                                   ValueToCppLiteral(axis->Values.front()));
        }

        emitted += "\n    return permutation;\n}\n\n";
        return emitted;
    }

    /** Mixed radix over the axes, in declaration order. This must match ComputeVariantIndex in
     * PermutationSpace.cpp exactly, because the cooker keys the tables with that one. */
    std::string EmitVariantIndex(const CookedModule& module)
    {
        const std::string moduleType = MakeTypeIdentifier(module.Name);
        const std::string typeName = std::format("{}Permutation", moduleType);
        std::string emitted = std::format(
            "constexpr uint32_t VariantIndex({} permutation) noexcept\n{{\n"
            "    permutation = Canonicalize(permutation);\n    uint32_t index = 0u;\n",
            typeName);

        for (const PermutationAxis* axis : *module.Space)
        {
            emitted += std::format("    index = index * {}u + IndexOf{}{}(permutation);\n",
                                   axis->Values.size(),
                                   moduleType,
                                   MakeFieldIdentifier(axis->Name));
        }

        emitted += "    return index;\n}\n\n";
        return emitted;
    }

} // namespace

std::string MakeFieldIdentifier(std::string_view axis_name)
{
    std::string identifier;
    identifier.reserve(axis_name.size());

    bool startOfWord = true;
    for (char character : axis_name)
    {
        if (character == '_')
        {
            startOfWord = true;
            continue;
        }

        const unsigned char raw = static_cast<unsigned char>(character);
        identifier += startOfWord ? static_cast<char>(std::toupper(raw))
                                  : static_cast<char>(std::tolower(raw));
        startOfWord = false;
    }

    return identifier;
}

std::string MakeModuleSourceFileName(std::string_view header_stem, std::string_view module_name)
{
    return std::format("{}_{}.cpp", header_stem, MakeTypeIdentifier(module_name));
}

std::string EmitShaderLibraryHeader(const CookedLibrary& library)
{
    std::string header;
    header.reserve(1u << 14);

    header += "#pragma once\n";
    header += k_GeneratedBanner;
    header += "#include \"shader/ShaderLibraryTypes.hpp\"\n";
    header += "#include <cstdint>\n#include <span>\n#include <string_view>\n\n";
    header += "namespace velox::shaders\n{\n\n";

    header += "enum class ModuleId : uint16_t\n{\n    Invalid = 0,\n";
    for (size_t i = 0u; i < library.Modules.size(); ++i)
    {
        header += std::format("    {} = {}u,\n", MakeTypeIdentifier(library.Modules[i].Name), i + 1u);
    }
    header += "};\n\n";

    header += "enum class EntryPointId : uint16_t\n{\n    Invalid = 0,\n";
    uint32_t entryPointOrdinal = 1u;
    for (const CookedModule& module : library.Modules)
    {
        for (const LibraryEntryPoint& entryPoint : module.EntryPoints)
        {
            header += std::format("    {} = {}u,\n", MakeTypeIdentifier(entryPoint.Name), entryPointOrdinal);
            ++entryPointOrdinal;
        }
    }
    header += "};\n\n";

    for (const CookedModule& module : library.Modules)
    {
        header += EmitPermutationStruct(module);

        for (const PermutationAxis* axis : *module.Space)
        {
            header += EmitAxisIndexHelper(module, *axis);
        }

        header += EmitCanonicalize(module);
        header += EmitVariantIndex(module);
    }

    header += "/** Returns the WGSL for one entry point of one variant. An unknown pair returns an\n"
              " * empty view, which createShaderModule rejects rather than silently accepting. */\n";
    header += "std::string_view GetSource(EntryPointId entry_point, uint32_t variant_index) noexcept;\n";
    header += "std::span<const velox::BindingInfo> GetBindings(EntryPointId entry_point,\n"
              "                                                uint32_t variant_index) noexcept;\n";
    header += "velox::WorkgroupSize GetWorkgroupSize(EntryPointId entry_point,\n"
              "                                      uint32_t variant_index) noexcept;\n";
    header += "velox::ShaderStageKind GetStage(EntryPointId entry_point) noexcept;\n\n";

    header += "/** The vertex attributes this entry point reads. Empty for every stage except vertex.\n"
              " * The semantic name survives here and nowhere in the WGSL, so a vertex buffer layout\n"
              " * can be checked against the shader by name. */\n";
    header += "std::span<const velox::VertexAttributeInfo> GetVertexInputs(EntryPointId entry_point,\n"
              "                                                            uint32_t variant_index) noexcept;\n";
    header += "std::span<const velox::ColorTargetInfo> GetColorTargets(EntryPointId entry_point,\n"
              "                                                        uint32_t variant_index) noexcept;\n";
    header += "/** True when the fragment shader writes SV_Depth. This is not depthWrite in RenderState.\n"
              " * A pass that writes depth from the shader while depthWrite is off is a real error. */\n";
    header += "bool GetWritesFragDepth(EntryPointId entry_point, uint32_t variant_index) noexcept;\n\n";

    header += "/** Serves the baked tables through the provider seam. Sources live in the data segment\n"
              " * for the life of the process, so Generation() never changes. A watch-and-serve cooker\n"
              " * implements the same interface and increments it instead. */\n";
    header += "class BakedShaderSourceProvider final : public velox::ShaderSourceProvider\n{\npublic:\n"
              "    BakedShaderSourceProvider() noexcept;\n"
              "    ~BakedShaderSourceProvider() override;\n\n"
              "    std::string_view Source(uint16_t entry_point, uint32_t variant_index) const noexcept override;\n"
              "    std::span<const velox::BindingInfo> Bindings(uint16_t entry_point,\n"
              "                                                 uint32_t variant_index) const noexcept override;\n"
              "    velox::WorkgroupSize Workgroup(uint16_t entry_point,\n"
              "                                   uint32_t variant_index) const noexcept override;\n"
              "    uint64_t Generation() const noexcept override;\n};\n\n";

    header += "} // namespace velox::shaders\n";
    return header;
}

std::string EmitShaderLibraryModuleSource(const CookedModule& module, std::string_view header_name)
{
    std::string source;
    source.reserve(1u << 20);

    source += k_GeneratedBanner;
    source += std::format("#include \"{}\"\n\n", header_name);
    source += "namespace velox::shaders\n{\n\nnamespace\n{\n\n";

    for (size_t i = 0u; i < module.Sources.size(); ++i)
    {
        source += std::format("constexpr std::string_view k_Source{} ={};\n\n",
                              i,
                              EmitChunkedLiteral(module.Sources[i]));
    }

    for (size_t i = 0u; i < module.Layouts.size(); ++i)
    {
        if (module.Layouts[i].empty())
        {
            source += std::format("constexpr velox::BindingInfo k_Layout{}[1]{{}};\n", i);
            source += std::format("constexpr uint32_t k_LayoutCount{} = 0u;\n\n", i);
            continue;
        }

        for (size_t bindingIndex = 0u; bindingIndex < module.Layouts[i].size(); ++bindingIndex)
        {
            source += EmitUniformMemberTable(module.Layouts[i][bindingIndex], i, bindingIndex);
        }

        source += std::format("constexpr velox::BindingInfo k_Layout{}[]{{\n", i);
        for (size_t bindingIndex = 0u; bindingIndex < module.Layouts[i].size(); ++bindingIndex)
        {
            const ReflectedBinding& binding = module.Layouts[i][bindingIndex];
            const std::string memberTableName =
                binding.UniformMembers.empty() ? std::string{}
                                               : MakeUniformMemberTableName(i, bindingIndex);
            source += EmitBindingRow(binding, memberTableName);
        }
        source += "};\n";
        source += std::format("constexpr uint32_t k_LayoutCount{} = {}u;\n\n",
                              i,
                              module.Layouts[i].size());
    }

    for (size_t i = 0u; i < module.RasterStates.size(); ++i)
    {
        source += EmitRasterState(module.RasterStates[i], i);
    }

    source += "struct VariantRecord\n{\n    std::string_view Source;\n"
              "    const velox::BindingInfo* Bindings;\n    uint32_t BindingCount;\n"
              "    velox::WorkgroupSize Workgroup;\n"
              "    const velox::VertexAttributeInfo* VertexInputs;\n    uint32_t VertexInputCount;\n"
              "    const velox::ColorTargetInfo* ColorTargets;\n    uint32_t ColorTargetCount;\n"
              "    bool WritesFragDepth;\n};\n\n";

    // One table for each entry point, indexed by the dense variant index. A dependent axis leaves
    // holes; those rows stay empty and every accessor reports them as unknown.
    for (size_t entryPointIndex = 0u; entryPointIndex < module.EntryPoints.size(); ++entryPointIndex)
    {
        std::vector<const LibraryVariant*> slots(module.SpaceSize, nullptr);
        for (const LibraryVariant& variant : module.Variants)
        {
            if (variant.Index < module.SpaceSize)
            {
                slots[variant.Index] = &variant;
            }
        }

        source += std::format("constexpr VariantRecord k_{}_Variants[{}]{{\n",
                              MakeTypeIdentifier(module.EntryPoints[entryPointIndex].Name),
                              module.SpaceSize);

        for (const LibraryVariant* variant : slots)
        {
            if (variant == nullptr)
            {
                source += "    VariantRecord{},\n";
                continue;
            }

            const uint32_t sourceIndex = variant->SourceIndices[entryPointIndex];
            const uint32_t layoutIndex = variant->LayoutIndices[entryPointIndex];
            const WorkgroupSize workgroup = variant->Workgroups[entryPointIndex];

            source += std::format("    VariantRecord{{ k_Source{}, k_Layout{}, k_LayoutCount{}, "
                                  "velox::WorkgroupSize{{ {}u, {}u, {}u }}, {} }},\n",
                                  sourceIndex,
                                  layoutIndex,
                                  layoutIndex,
                                  workgroup.X,
                                  workgroup.Y,
                                  workgroup.Z,
                                  EmitRasterRecordFields(variant->RasterIndices[entryPointIndex]));
        }

        source += "};\n\n";
    }

    source += std::format("constexpr uint32_t k_VariantSpaceSize = {}u;\n\n", module.SpaceSize);

    source += "const VariantRecord* FindRecord(EntryPointId entry_point, uint32_t variant_index) noexcept\n"
              "{\n    if (variant_index >= k_VariantSpaceSize)\n    {\n        return nullptr;\n    }\n\n"
              "    switch (entry_point)\n    {\n";
    for (const LibraryEntryPoint& entryPoint : module.EntryPoints)
    {
        const std::string identifier = MakeTypeIdentifier(entryPoint.Name);
        source += std::format("    case EntryPointId::{}:\n        return &k_{}_Variants[variant_index];\n",
                              identifier,
                              identifier);
    }
    source += "    default:\n        return nullptr;\n    }\n}\n\n";

    source += "} // namespace\n\n";

    source += "std::string_view GetSource(EntryPointId entry_point, uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    return record != nullptr ? record->Source : std::string_view{};\n}\n\n";

    source += "std::span<const velox::BindingInfo> GetBindings(EntryPointId entry_point,\n"
              "                                                uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    if (record == nullptr || record->BindingCount == 0u)\n    {\n        return {};\n    }\n\n"
              "    return std::span<const velox::BindingInfo>{ record->Bindings, record->BindingCount };\n}\n\n";

    source += "velox::WorkgroupSize GetWorkgroupSize(EntryPointId entry_point,\n"
              "                                      uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    return record != nullptr ? record->Workgroup : velox::WorkgroupSize{};\n}\n\n";

    source += "std::span<const velox::VertexAttributeInfo> GetVertexInputs(EntryPointId entry_point,\n"
              "                                                            uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    if (record == nullptr || record->VertexInputCount == 0u)\n    {\n        return {};\n    }\n\n"
              "    return std::span<const velox::VertexAttributeInfo>{ record->VertexInputs,\n"
              "                                                        record->VertexInputCount };\n}\n\n";

    source += "std::span<const velox::ColorTargetInfo> GetColorTargets(EntryPointId entry_point,\n"
              "                                                        uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    if (record == nullptr || record->ColorTargetCount == 0u)\n    {\n        return {};\n    }\n\n"
              "    return std::span<const velox::ColorTargetInfo>{ record->ColorTargets,\n"
              "                                                    record->ColorTargetCount };\n}\n\n";

    source += "bool GetWritesFragDepth(EntryPointId entry_point, uint32_t variant_index) noexcept\n"
              "{\n    const VariantRecord* record = FindRecord(entry_point, variant_index);\n"
              "    return record != nullptr ? record->WritesFragDepth : false;\n}\n\n";

    source += "velox::ShaderStageKind GetStage(EntryPointId entry_point) noexcept\n{\n    switch "
              "(entry_point)\n    {\n";
    for (const LibraryEntryPoint& entryPoint : module.EntryPoints)
    {
        source += std::format("    case EntryPointId::{}:\n        return {};\n",
                              MakeTypeIdentifier(entryPoint.Name),
                              EnumeratorFor("ShaderStageKind", ToString(entryPoint.Stage)));
    }
    source += "    default:\n        return velox::ShaderStageKind::Invalid;\n    }\n}\n\n";

    source += "BakedShaderSourceProvider::BakedShaderSourceProvider() noexcept = default;\n"
              "BakedShaderSourceProvider::~BakedShaderSourceProvider() = default;\n\n"
              "std::string_view BakedShaderSourceProvider::Source(uint16_t entry_point,\n"
              "                                                  uint32_t variant_index) const noexcept\n"
              "{\n    return GetSource(static_cast<EntryPointId>(entry_point), variant_index);\n}\n\n"
              "std::span<const velox::BindingInfo> BakedShaderSourceProvider::Bindings(\n"
              "    uint16_t entry_point,\n    uint32_t variant_index) const noexcept\n"
              "{\n    return GetBindings(static_cast<EntryPointId>(entry_point), variant_index);\n}\n\n"
              "velox::WorkgroupSize BakedShaderSourceProvider::Workgroup(uint16_t entry_point,\n"
              "                                                         uint32_t variant_index) const noexcept\n"
              "{\n    return GetWorkgroupSize(static_cast<EntryPointId>(entry_point), variant_index);\n}\n\n"
              "uint64_t BakedShaderSourceProvider::Generation() const noexcept\n{\n    return 1u;\n}\n\n";

    source += "} // namespace velox::shaders\n";
    return source;
}

} // namespace velox::cooker
